services:
  postgres-orders:
    image: postgres:15
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Your_password123"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ordersdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5434:5432"

  postgres-payments:
    image: postgres:15
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Your_password123"
    volumes:
      - payments-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paymentsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5672:5672"
      - "15672:15672"

  orders-service:
    build: ./OrderService
    depends_on:
      postgres-orders:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: >
        Host=postgres-orders;
        Port=5432;
        Database=ordersdb;
        Username=postgres;
        Password=Your_password123;
      RabbitMq__Host: rabbitmq
      RabbitMq__QueueName: order-events
    ports:
      - "5001:80"

  payments-service:
    build: ./PaymentsService
    depends_on:
      postgres-payments:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: >
        Host=postgres-payments;
        Port=5432;
        Database=paymentsdb;
        Username=postgres;
        Password=Your_password123;
      RabbitMq__Host: rabbitmq
      RabbitMq__InQueue: order-events
      RabbitMq__OutQueue: payment-events
    ports:
      - "5002:80"

  api-gateway:
    build: ./ApiGateway
    depends_on:
      - orders-service
      - payments-service
    environment:
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5003:80"

volumes:
  orders-db-data:
  payments-db-data:
